### ISSUE TITLE
View recent sessions

### ISSUE THREAD

**Issue by SebastianStehle** [tarampampam/webhook-tester#259] opened 2023-02-20 16:21 UTC
Hi,

great tool. I use it for my tests but I am missing one feature. I great the sessions inside my tests and then delete it in the teardown. I would like to have a feature to view the latest session ids somewhere, so that I can jump into that without having to debug or log the session Id in my tests.

**Comment by hirenshah** [comment] 2023-05-21 19:29
This would be a useful feature 👍

**Comment by tarampampam** [comment] 2024-11-02 18:53
Hello! Apologies for the late response, but I have good news - I've added the requested feature, along with a number of other improvements I made while working on version 2 of the app.

It would be great if you could try out the early test build and share your feedback. Do all the features work as expected? Did you encounter any crashes, or notice anything that isn’t functioning as intended?

The Docker image and precompiled binary files are available at this link: https://github.com/tarampampam/webhook-tester/releases/tag/v2.0.0-alpha1

**Comment by tarampampam** [comment] 2024-12-06 14:35
Check out the new release [v2.0.0](https://github.com/tarampampam/webhook-tester/releases/tag/v2.0.0) (or a later version). If you encounter any errors or unexpected behavior, feel free to open a new issue. I'll be closing this one :)

**Closed by tarampampam** 2024-12-06 14:35 UTC

**Comment by SebastianStehle** [comment] 2024-12-06 16:25
Thank yo, but this is not what i was looking for. I get a list of all requests, but not a list of current sessions

**Comment by tarampampam** [comment] 2024-12-07 13:00
You will see the list of sessions once you have more than one:

![image](https://github.com/user-attachments/assets/62871232-2860-4202-bd71-160038836626)
